[[constraint]]
  name = "cloud.google.com/go"
  version = "0.25.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
